CREATE TABLE IF NOT EXISTS agents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  hlc_code VARCHAR(100) NULL,
  first_name VARCHAR(150) NULL,
  last_name VARCHAR(150) NULL,
  middle_name VARCHAR(150) NULL,
  role VARCHAR(100) NULL,
  personal_email VARCHAR(255) NULL,
  zonal_email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NULL,
  password_hash VARCHAR(255) NULL,
  mobile_number VARCHAR(50) NULL,
  address TEXT NULL,
  birth_date DATE NULL,
  birth_place VARCHAR(255) NULL,
  civil_status VARCHAR(100) NULL,
  gender VARCHAR(100) NULL,
  recruiter VARCHAR(255) NULL,
  accredited_date DATE NULL,
  locality VARCHAR(100) NULL,
  team VARCHAR(100) NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'For Approval',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY agents_zonal_email_unique (zonal_email),
  KEY agents_status_index (status)
);

CREATE TABLE IF NOT EXISTS developers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  developer_name VARCHAR(255) NOT NULL,
  project VARCHAR(255) NOT NULL,
  lts VARCHAR(100) NULL,
  developer_rate DECIMAL(8, 2) NOT NULL DEFAULT 0,
  assigned_lsd VARCHAR(255) NULL,
  project_location VARCHAR(255) NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Active',
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY developers_status_index (status)
);

CREATE TABLE IF NOT EXISTS brs_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  payload JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS commission_vouchers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  payload JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS commission_computations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  payload JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
